#:schema node_modules/wrangler/config-schema.json
name = "domain-availability-checker"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[triggers]
crons = ["0 */3 * * *"]
